[env:m5dial]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  https://github.com/m5stack/M5Dial.git
  milesburton/DallasTemperature @ ^3.11.0
  paulstoffregen/OneWire @ ^2.3.8
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^7.0.4
  tzapu/WiFiManager @ ^2.0.17
